name: Continuous Delivery

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn  

      - name: Run deploy script
        run: yarn deploy